[package]
name = "panamax"
version = "0.2.0"
authors = ["k3d3 <k@3d3.ca>"]
description = "Mirror rustup and crates.io repositories, for offline Rust and Cargo usage."
license = "MIT/Apache-2.0"
readme = "README.md"
homepage = "https://github.com/k3d3/panamax"
repository = "https://github.com/k3d3/panamax"
edition = "2018"

[dependencies]
reqwest = "0.9.19"
indicatif = "0.11.0"
structopt = "0.2.18"
toml = "0.5.1"
serde_derive = "1.0.94"
serde = "1.0.94"
quick-error = "1.2.2"
console = "0.7.7"
scoped_threadpool = "0.1.9"
log = "0.4.7"
env_logger = "0.6.2"
sha2 = "0.8.0"
url = "1.7.2"
glob = "0.3.0"
git2 = "0.9.1"
serde_json = "1.0.40"
