# This is a Panamax mirror. It is a self-contained directory made to be easily copied
# to an air-gapped network or machine via rsync, USB, or another method.

# While Panamax handles grabbing files from the Internet, it does not handle hosting
# on the air-gapped side. Since everything in the mirror is static, it should be
# fairly easily hosted using nginx, and git for the crates.io-index mirror.

[mirror]
# Global mirror settings.

# Number of download retries before giving up.
retries = 5

# Contact information for the user agent.
# As per crates.io crawling policy, lacking this information may cause your IP to be blocked.
# It's recommended that this be set to your email address or a website you own.
# If you're okay with this, this parameter can be removed.
contact = "your@email.com"

# URL where this mirror will be accessed from.
# Used for rewriting crates.io-index's config.json.
# Remove this parameter to perform no rewriting.
base_url = "http://panamax.internal"

[rustup]
# These are the configuration parameters for the rustup half of the mirror.
# This will download the rustup-init files, as well as all components needed
# to run Rust on a machine.

# Perform rustup synchronization. Set this to false if you only want to mirror crates.io.
sync = true

# Number of download threads to use when downloading rustup components.
# This should be set lower than crates, as rustup consists of large files.
download_threads = 4

# Where to download rustup files from.
source = "https://static.rust-lang.org"

# How many historical versions of Rust to keep.
# Setting these to 1 will keep only the latest version.
# Setting these to 2 or higher will keep the latest version, as well as historical versions.
# Setting these to 0 will stop Panamax from downloading the release entirely.
# Removing the line will keep all release versions.
keep_latest_stables = 1
keep_latest_betas = 1
keep_latest_nightlies = 1

[crates]
# These are the configuration parameters for the crates.io half of the mirror.
# This will download the crates.io-index, as well as the crates themselves.
# Once downloaded, it will then (optionally) rewrite the config.json to point to your mirror.

# Perform crates synchronization. Set this to false if you only want to mirror rustup.
sync = true

# Number of download threads to use when downloading crates components.
# This should be set higher than rustup, as crates consist of many small files.
download_threads = 16

# Where to download the crates from.
source = "https://crates.io/api/v1/crates"

# Where to clone the crates.io-index repository from.
source_index = "https://github.com/rust-lang/crates.io-index"
